# Generated by Django 4.2.29 on 2026-03-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesonl', '0002_test_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='topic',
        ),
    ]
