# Generated by Django 4.2.29 on 2026-04-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesonl', '0003_remove_test_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
